# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c27e27061498e2893ef1618169bf9f69ef662c493a1ebc2c51cff8d31f35649fd4f6718b49e1c7205760a52e6ef869253106d891678a355f17f9d1a6ace8c51

test:
  secret_key_base: 49c9900cf38cda0328fe31381f349fc60f1e7ec44126c3a18e3ba1dc01d765d92ced081fd50c173cd779d9bef9dbd711e3d5f38a59fa4f72d09f38b3a4cdddc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
